# Generated by Django 3.2 on 2022-01-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nomnbre')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('fecha_publicación', models.DateTimeField(verbose_name='Fecha de Publicaión')),
                ('fecha_ultima_modificacion', models.DateTimeField(verbose_name='Fecha de Publicaión')),
                ('visible', models.BooleanField()),
            ],
        ),
    ]
