# Generated by Django 3.2 on 2022-01-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_post_contenido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='fecha_publicación',
            new_name='fecha_publicacion',
        ),
    ]
