# Generated by Django 3.2 on 2022-01-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_auto_20220121_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(blank=True, verbose_name='Fecha de Publicaión'),
        ),
    ]
