# Generated by Django 3.2 on 2022-01-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_alter_post_fecha_ultima_modificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fecha_ultima_modificacion',
        ),
    ]
