# Generated by Django 3.2 on 2022-02-09 03:44

from django.db import migrations, models
import django.db.models.deletion
import post_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0011_auto_20220208_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_post',
            name='img',
            field=models.ImageField(upload_to=post_app.models.post_image_paht, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='image_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='imagenes', to='post_app.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tema', to='post_app.temas', verbose_name='Tema'),
        ),
    ]
