# Generated by Django 3.2 on 2022-02-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0013_alter_post_tema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
