# Generated by Django 3.2 on 2022-02-20 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0019_alter_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Contenido'),
        ),
    ]
